import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'
import localizationPatches from './localizationPatches'

export const LANGUAGE_OPTIONS = [
  {
    code: 'en',
    label: 'English',
    nativeLabel: 'English',
    speechLang: 'en-US',
    recognitionLang: 'en-US',
    voiceSearch: ['Google UK English Female', 'Google US English', 'Microsoft Zira', 'Samantha', 'Karen', 'Moira', 'Tessa'],
  },
  {
    code: 'de',
    label: 'German',
    nativeLabel: 'Deutsch',
    speechLang: 'de-DE',
    recognitionLang: 'de-DE',
    voiceSearch: ['Google Deutsch', 'Microsoft Katja', 'Anna'],
  },
  {
    code: 'bg',
    label: 'Bulgarian',
    nativeLabel: 'Български',
    speechLang: 'bg-BG',
    recognitionLang: 'bg-BG',
    voiceSearch: ['Bulgarian', 'bg-BG', 'Daria'],
    voiceNote: 'Bulgarian browser voices са често липсващи. Ако браузърът няма BG voice, JobSensei ще използва fallback и може да звучи странно.',
  },
  {
    code: 'ru',
    label: 'Russian',
    nativeLabel: 'Русский',
    speechLang: 'ru-RU',
    recognitionLang: 'ru-RU',
    voiceSearch: ['Google русский', 'Microsoft Irina', 'Milena'],
  },
  {
    code: 'es-ES',
    label: 'Spanish (Spain)',
    nativeLabel: 'Español',
    speechLang: 'es-ES',
    recognitionLang: 'es-ES',
    dictionary: 'es',
    voiceSearch: ['Google español', 'Microsoft Elvira', 'Monica'],
  },
  {
    code: 'fr',
    label: 'French',
    nativeLabel: 'Français',
    speechLang: 'fr-FR',
    recognitionLang: 'fr-FR',
    voiceSearch: ['Google français', 'Microsoft Hortense', 'Amelie', 'Aurelie', 'Audrey'],
  },
  {
    code: 'it',
    label: 'Italian',
    nativeLabel: 'Italiano',
    speechLang: 'it-IT',
    recognitionLang: 'it-IT',
    voiceSearch: ['Google italiano', 'Microsoft Elsa', 'Alice'],
  },
  {
    code: 'pl',
    label: 'Polish',
    nativeLabel: 'Polski',
    speechLang: 'pl-PL',
    recognitionLang: 'pl-PL',
    voiceSearch: ['Google polski', 'Microsoft Paulina', 'Zosia'],
  },
  {
    code: 'pt-BR',
    label: 'Portuguese (Brazil)',
    nativeLabel: 'Português',
    speechLang: 'pt-BR',
    recognitionLang: 'pt-BR',
    dictionary: 'pt',
    voiceSearch: ['Google português do Brasil', 'Google português', 'Microsoft Francisca', 'Maria', 'Luciana', 'pt-BR'],
  },
]

const TRANSLATIONS = {
  en: {
    'nav.today': 'Today',
    'nav.applications': 'Applications',
    'nav.learning': 'Learning',
    'nav.settings': 'Settings',
    'nav.projects': 'Projects',
    'nav.apps': 'Apps',
    'nav.learn': 'Learn',
    'brand.tagline': 'Be confident. Get hired.',
    'common.rename': 'Rename',
    'common.export': 'Export',
    'common.delete': 'Delete',
    'common.collapse': 'Collapse',
    'common.expand': 'Expand',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.add': 'Add',
    'common.close': 'Close',
    'applications.title': 'Applications',
    'applications.subtitle': '{count} applications in your workspace',
    'applications.exportJobs': 'Export Jobs',
    'applications.importJobs': 'Import Jobs',
    'applications.sync': 'Sync',
    'applications.synced': 'Synced',
    'applications.importedMany': 'Imported {count} applications',
    'applications.invalidFile': 'Invalid file',
    'applications.setActive': 'Set Active',
    'applications.followUpToday': 'Follow Up Today ({count})',
    'applications.empty.addFirst': 'Add applications first.',
    'applications.tabs.kanban': 'Kanban',
    'applications.tabs.workspace': 'Workspace',
    'applications.tabs.offers': 'Offers',
    'applications.tabs.stats': 'Stats',
    'applications.tabs.unknown': '{tab}',
    'applications.stage.researching': 'Researching',
    'applications.stage.applied': 'Applied',
    'applications.stage.screening': 'Screening',
    'applications.stage.interviewing': 'Interviewing',
    'applications.stage.awaiting': 'Awaiting',
    'applications.stage.offer': 'Offer',
    'applications.stage.rejected': 'Rejected',
    'applications.stage.unknown': '{stage}',
    'applications.badges.active': 'Active',
    'applications.badges.jdAttached': 'JD attached',
    'applications.badges.noJd': 'No JD',
    'applications.badges.research': 'Research',
    'applications.badges.notes': 'Notes',
    'applications.badges.researchReady': 'Research ready',
    'applications.badges.prepNotes': 'Prep notes',
    'applications.add.kicker': 'Create Application Workspace',
    'applications.add.title': 'Start one role, then let JobSensei guide the rest',
    'applications.add.copy': 'Add the company and role first. The JD, AI research, and prep note can be added now or later without breaking the workflow.',
    'applications.add.readiness.title': 'Readiness',
    'applications.add.readiness.count': '{count}/4 signals ready',
    'applications.add.readiness.company': 'Company',
    'applications.add.readiness.role': 'Role',
    'applications.add.readiness.jd': 'JD',
    'applications.add.readiness.research': 'Research',
    'applications.add.required': 'Required',
    'applications.add.recommended': 'Recommended',
    'applications.add.saved': 'Saved',
    'applications.add.addNowOrLater': 'Add now or later',
    'applications.add.readyLive': 'Ready (live)',
    'applications.add.readyAi': 'Ready (AI)',
    'applications.add.optionalAiAssist': 'Optional AI assist',
    'applications.add.connectAiSettings': 'Connect AI in Settings',
    'applications.add.createOpenWorkspace': 'Create & open workspace',
    'applications.add.createAddJdLater': 'Create & add JD later',
    'applications.add.openImmediately': 'You can open the full workspace immediately.',
    'applications.add.addJdLaterHelp': 'You can still create now and add the JD inside the workspace.',
    'applications.add.jdHelp': 'Recommended. If you skip this now, you can paste it later from the Capture step inside the workspace.',
    'applications.add.researchReadyLive': 'Research ready (live data)',
    'applications.add.researchReadyAi': 'Research ready (AI)',
    'applications.add.researchReadyCopy': 'Wow facts, culture, and prep notes will be saved into Research.',
    'applications.add.researchPrefix': 'Research',
    'applications.add.researchSuffix': 'with AI',
    'applications.add.researchCopy': 'Pull wow facts, news, culture, and prep notes before you create the workspace.',
    'applications.add.researching': 'Researching...',
    'applications.add.rerun': 'Re-run',
    'applications.add.research': 'Research',
    'applications.add.savedTo': 'Saved to',
    'applications.add.myPrepNotes': 'Research / My prep notes',
    'applications.add.whenCreated': 'when you create the application.',
    'applications.add.saveToBoardOnly': 'Save to board only',
    'applications.fields.companyRequired': 'Company *',
    'applications.fields.roleTitle': 'Role title',
    'applications.fields.stage': 'Stage',
    'applications.fields.jdUrl': 'JD URL',
    'applications.fields.jobDescription': 'Job Description',
    'applications.fields.initialPrepNote': 'Initial prep note',
    'applications.placeholders.company': 'e.g. TBI Bank',
    'applications.placeholders.roleTitle': 'e.g. Fraud Detection Analyst',
    'applications.placeholders.jdUrl': 'Optional source link',
    'applications.placeholders.jobDescription': 'Paste the job description once to make this application available across the main tools...',
    'applications.placeholders.initialPrepNote': 'Optional reminders, talking points, or recruiter context...',
    'applications.placeholders.editJobDescription': 'Paste the saved job description for this application...',
    'applications.edit.title': 'Edit Application',
    'applications.stats.total': 'Total',
    'applications.stats.active': 'Active',
    'applications.stats.offers': 'Offers',
    'applications.stats.rejected': 'Rejected',
    'applications.stats.pipeline': 'Pipeline',
    'applications.stats.offerCount': '{count} Offer!',
    'applications.stats.conversion': 'Conversion: {percent}%',
    'applications.workspaceTabs.workspace': 'Workspace',
    'applications.workspaceTabs.capture': 'Capture',
    'applications.workspaceTabs.research': 'Research',
    'applications.workspace.back': 'Back to Applications',
    'applications.workspace.defaultTitle': 'Application workspace',
    'applications.workspace.activeWorkspace': 'Active workspace',
    'applications.workspace.save': 'Save Workspace',
    'applications.workspace.saved': 'Saved!',
    'applications.workspace.status.complete': 'Complete',
    'applications.workspace.status.inProgress': 'In Progress',
    'applications.workspace.status.blocked': 'Blocked',
    'applications.workspace.status.ready': 'Ready',
    'applications.offer.salary': 'Salary',
    'applications.offer.growth': 'Growth',
    'applications.offer.culture': 'Culture',
    'applications.offer.workLife': 'Work-Life',
    'applications.offer.benefits': 'Benefits',
    'applications.offer.flexibility': 'Flexibility',
    'applications.offer.noOffers': 'No Offers Yet',
    'applications.offer.noOffersCopy': 'Move an application to "Offer" stage to compare here.',
    'applications.offer.whatMatters': 'What matters to you?',
    'applications.offer.hide': 'Hide up',
    'applications.offer.customizeWeights': 'Customize weights down',
    'applications.offer.weightTotal': 'Total: {total}%',
    'applications.offer.adjustWeights': '- adjust sliders to reach 100%',
    'applications.offer.weightOk': 'OK',
    'applications.offer.currentLeader': 'Current Leader',
    'projects.title': 'Projects',
    'projects.noProject': 'No project',
    'projects.new': 'New Project',
    'projects.namePlaceholder': 'Project name...',
    'projects.namePlaceholderShort': 'Project name…',
    'projects.exportAll': 'Export All',
    'projects.exportAllProjects': 'Export All Projects',
    'projects.exportCurrentProject': 'Export Project',
    'projects.import': 'Import',
    'projects.importProject': 'Import Project',
    'projects.importing': 'Importing...',
    'projects.importingShort': 'Importing…',
    'projects.importedOne': '✅ Imported 1 project',
    'projects.importedMany': '✅ Imported {count} projects',
    'projects.invalidFile': '❌ Invalid file',
    'projects.confirmDelete': 'Delete "{name}"?',
    'topbar.guide': 'Guide',
    'topbar.start': 'Start',
    'topbar.aiConnected': 'AI Connected',
    'topbar.locked': 'Locked',
    'topbar.thinking': 'Thinking...',
    'topbar.sensei': 'Sensei',
    'topbar.drill': 'Drill',
    'guide.helpTitle': 'Help: {section}',
    'guide.getStarted': 'Get started',
    'guide.startTour': 'Start guided tour',
    'guide.howThisPageWorks': 'How this page works',
    'guide.footer.sensei': 'Sensei = supportive coaching',
    'guide.footer.drill': 'Drill = brutal honesty',
    'guide.today.title': 'Today',
    'guide.today.desc': 'Your daily command center. Pick one active application and JobSensei shows the next useful move.',
    'guide.today.detail.activeFocus': 'Active Focus is the current role JobSensei is guiding.',
    'guide.today.detail.progress': 'Workspace Progress shows the 6-step application path: capture, research, tailor, predict, mock, follow-up.',
    'guide.today.detail.workspace': 'Open the active workspace for research, JD, prep notes, and follow-up.',
    'guide.applications.title': 'Applications',
    'guide.applications.desc': 'Your CRM for job hunting. Each role has its own workspace so research, JD text, notes, tools, and follow-up stay together.',
    'guide.applications.detail.kanban': 'Kanban tracks stages like Researching, Applied, Interviewing, Offer, and Rejected.',
    'guide.applications.detail.workspace': 'Workspace is where the JD, research, prep notes, and cheat sheet live for one role.',
    'guide.applications.detail.offers': 'Offers compares roles by salary, growth, culture, work-life, benefits, and flexibility.',
    'guide.dashboard.title': 'Dashboard',
    'guide.dashboard.desc': 'Your home base. See your stats, daily tips, and quick links to every tool.',
    'guide.dashboard.tip.streak': 'Check your streak and interview count here',
    'guide.dashboard.tip.quickJump': 'Quick-jump to any tool from the cards below',
    'guide.dashboard.detail.gated': 'Dashboard is gated until an application exists.',
    'guide.dashboard.detail.unlocked': 'Once unlocked, it shows saved interviews, learning progress, active application context, and quick actions.',
    'guide.interview.title': 'Interview Prep',
    'guide.interview.desc': 'Practice interviews, predict likely questions, polish STAR stories, and tighten your follow-up.',
    'guide.interview.tip.simulator': 'Use the Interview Simulator for full mock sessions',
    'guide.interview.tip.hub': 'Question Predictor and STAR Builder now live under this prep hub',
    'guide.interview.tip.history': 'Saved prep history still stays inside each tool',
    'guide.interview.detail.simulator': 'Interview Simulator runs full mock sessions and saves score/history.',
    'guide.interview.detail.predictor': 'Question Predictor uses the active JD to generate likely questions.',
    'guide.interview.detail.star': 'STAR Builder turns rough stories into structured answers.',
    'guide.interview.detail.tone': 'Tone Analyzer checks clarity, confidence, and delivery.',
    'guide.interview.detail.followUp': 'Follow-up Email drafts post-interview messages.',
    'guide.interview.detail.pitch': 'Elevator Pitch helps answer why you should be hired.',
    'guide.gap.title': 'Gap Analysis',
    'guide.gap.desc': 'Paste a job description + your background. AI identifies skill gaps and strengths.',
    'guide.gap.tip.jd': 'Paste the full JD in the first box',
    'guide.gap.tip.cv': 'Paste your CV/background in the second',
    'guide.gap.tip.score': 'Get a match score and action plan',
    'guide.learning.title': 'Learning',
    'guide.learning.desc': 'Study topics with an AI tutor, then test yourself with quizzes. Spaced repetition keeps reviews smart.',
    'guide.learning.saveLastResponseLabel': 'Save last response to Notes',
    'guide.learning.detail.topics': 'Build own topics for the skills the target role expects.',
    'guide.learning.detail.saveNotes': 'Save last response to Notes stores useful tutor replies in Learning Notes',
    'guide.learning.detail.quiz': 'Click Quiz for a 6-question test on that topic and chat history.',
    'guide.learning.detail.reviews': "Due reviews appear at the top - don't skip them!",
    'guide.star.title': 'STAR Builder',
    'guide.star.desc': 'Turn rough situation notes into polished STAR (Situation-Task-Action-Result) interview answers.',
    'guide.star.tip.newStory': 'Click New Story and describe what happened (rough notes are fine)',
    'guide.star.tip.structure': 'AI structures it into a full STAR answer',
    'guide.star.tip.save': 'Save to your Story Bank, then view or copy anytime',
    'guide.tools.title': 'Prep Tools',
    'guide.tools.desc': 'Focused AI tools for the active application: fit checks, resume review, cover letter, LinkedIn, and visual resume feedback.',
    'guide.tools.tip.activeApplication': 'Set an active application first for better context',
    'guide.tools.tip.visualReview': 'Use Visual Review with a vision-capable model',
    'guide.tools.tip.history': 'Recent results stay saved to project history',
    'guide.tools.detail.gap': 'Gap Analysis scores fit against the JD and calls out missing skills.',
    'guide.tools.detail.resume': 'Resume Checker reads the resume through ATS and recruiter lenses.',
    'guide.tools.detail.coverLetter': 'Cover Letter Optimizer creates role-specific versions.',
    'guide.tools.detail.linkedin': 'LinkedIn Auditor finds profile gaps and quick wins.',
    'guide.tools.detail.visual': 'Visual Design Review checks layout from a screenshot.',
    'guide.tools.detail.transferable': 'Transferable Skills Coach reframes experience for a new role.',
    'guide.tracker.title': 'Applications',
    'guide.tracker.desc': 'Track every application, open a workspace for each role, and keep one active context flowing through the prep tools.',
    'guide.tracker.tip.add': 'Add a new application with the + button',
    'guide.tracker.tip.openCard': 'Open a card to work on that application in context',
    'guide.tracker.tip.active': 'Set one application active so your prep tools stay aligned',
    'guide.tracker.detail.add': 'Use Add for a new role or the browser extension to capture a JD.',
    'guide.tracker.detail.workspace': 'Open Workspace to work inside one application.',
    'guide.tracker.detail.offers': 'Use the Offers tab after a role reaches Offer stage.',
    'guide.notes.title': 'Notes & Workbook',
    'guide.notes.desc': 'A free-form scratchpad for your job search. My Notes is your personal workspace; Company Notes lets you keep notes per company.',
    'guide.notes.tip.autosave': 'Everything auto-saves as you type',
    'guide.notes.tip.companyNotes': 'Use Company Notes to track research per company',
    'guide.notes.tip.project': 'Notes are saved per project',
    'guide.settings.title': 'Settings',
    'guide.settings.desc': 'Unlock JobSensei, choose hosted AI or BYOK, save your resume, and back up project data.',
    'guide.settings.detail.connect': 'Connect AI first if tools are locked.',
    'guide.settings.detail.resume': 'Save your resume here so Resume Checker, Cover Letter, and prep tools can reuse it.',
    'guide.settings.detail.backups': 'Export project backups before changing devices or browsers.',
    'guide.settings.detail.byok': 'BYOK still requires an active JobSensei unlock',
    'tour.stepCounter': 'Step {current} of {total}',
    'tour.back': 'Back',
    'tour.next': 'Next',
    'tour.finish': 'Finish',
    'tour.guide.title': 'Start with Guide',
    'tour.guide.body': 'Use Guide any time you feel lost. It explains the current page and can restart this walkthrough.',
    'tour.today.title': 'Today shows the next move',
    'tour.today.body': 'This area is the daily command center. Before an application exists, it points you to the first application step.',
    'tour.addApplication.title': 'Add the first application',
    'tour.addApplication.body': 'Press Add to create the workspace. Add company, role, and the JD so every tool can use the same context.',
    'tour.workspace.title': 'Workspace keeps the role together',
    'tour.workspace.body': 'Workspace is where you review the JD, research the company, save notes, and generate prep material for one role.',
    'tour.offers.title': 'Offers compares final choices',
    'tour.offers.body': 'When an application reaches Offer, this tab helps compare salary, growth, culture, work-life, benefits, and flexibility.',
    'tour.learning.title': 'Learning is the long game',
    'tour.learning.body': 'Add topics for the skills each role expects. Study, quiz, and save notes so preparation compounds over time.',
    'tour.projects.title': 'Create own Projects',
    'tour.projects.body': 'Projects keep each job search separate: applications, resume/CV, notes, interview prep, learning topics, and saved AI results stay inside the selected project. Use New Project for a fresh workspace.',
    'gate.title': 'Add an application first',
    'gate.copy': '{section} works best when JobSensei knows the company, role, and job description. Create or capture one real application first, then the tools will unlock with the right context.',
    'gate.add': 'Add Application',
    'gate.back': 'Back to Today',
    'today.hello': 'Hello, {name}',
    'today.subtitle': 'One place to see the next real move in your job search.',
    'today.activeFocus': 'Active Focus',
    'today.startFirst': 'Start your first application',
    'today.startCopy': 'Add a company and role first. JobSensei will turn it into one guided workspace with research, story prep, practice, and follow-up.',
    'today.openApplications': 'Open Applications',
    'today.applications': 'Applications',
    'today.workspaceProgress': 'Workspace Progress',
    'today.pickApplication': 'Pick an application to begin',
    'today.rolesInPlay': 'Roles currently in play',
    'today.mockInterviews': 'Mock Interviews',
    'today.savedProject': 'Saved in this project',
    'today.reviewsDue': 'Reviews Due',
    'today.noReviews': 'No reviews due right now',
    'today.firstStep': 'First step',
    'today.firstStepTitle': 'Add one real application to unlock the workspace',
    'today.firstStepCopy': 'Start with the company, role, and job description. After that, Interview Prep, Prep Tools, research, follow-ups, and offer comparison all connect to that one application instead of feeling random.',
    'today.prepHubs': 'Prep Hubs',
    'today.prepHubsCopy': 'Two clear places to continue: interview practice or document/profile prep.',
    'today.hero.default': 'Use Today to keep the right application moving without bouncing between tools.',
    'today.hero.suggested': 'No application is active right now, so Today is recommending {application} as your next focus.',
    'today.hero.next': 'Next up: {title}. {desc}',
    'today.hero.complete': 'Your core workflow is complete for this application. Keep practicing, following up, or refining advanced tools.',
    'today.continueStep': 'Continue {title}',
    'today.openWorkspace': 'Open Workspace',
    'today.workspace': 'Workspace',
    'today.suggestedFocus': 'Suggested focus',
    'today.jdReady': 'JD ready',
    'today.needsJd': 'Needs JD',
    'today.changeActiveApplication': 'Change active application',
    'today.metric.next': 'Next: {title}',
    'today.metric.coreComplete': 'Core flow complete',
    'today.oneRoleInPlay': 'One role in play',
    'today.savedForApplication': 'Saved for this application',
    'today.learningReviewsDue': 'Learning reviews due today',
    'today.steps.addJdFirst': 'Add JD First',
    'today.steps.capture.title': 'Capture Job',
    'today.steps.capture.done': 'The JD is saved and powering the rest of the application workflow.',
    'today.steps.capture.todo': 'Paste the JD once so research, prediction, and interviews stay aligned.',
    'today.steps.capture.review': 'Review Capture',
    'today.steps.capture.addJd': 'Add JD',
    'today.steps.research.title': 'Research Company',
    'today.steps.research.done': 'Company context is saved and ready to reuse across the workspace.',
    'today.steps.research.todo': 'Add wow facts, culture signals, and open questions before practicing.',
    'today.steps.research.review': 'Review Research',
    'today.steps.research.open': 'Open Research',
    'today.steps.tailor.title': 'Tailor Story',
    'today.steps.tailor.done': 'You already have saved tailoring work for this role.',
    'today.steps.tailor.todo': 'Use gap analysis and STAR stories to make your answers sound role-specific.',
    'today.steps.tailor.openGap': 'Open Gap Analysis',
    'today.steps.predict.title': 'Predict Questions',
    'today.steps.predict.done': 'A question set is already saved for this role.',
    'today.steps.predict.todo': 'Generate likely interview questions from the saved JD.',
    'today.steps.predict.open': 'Open Predictor',
    'today.steps.mock.title': 'Mock Interview',
    'today.steps.mock.done': 'You already have a saved mock interview for this role.',
    'today.steps.mock.todo': 'Run a role-specific practice interview and save the session.',
    'today.steps.mock.start': 'Start Mock Interview',
    'today.steps.followup.title': 'Follow-up',
    'today.steps.followup.done': 'A follow-up draft is already saved for this application.',
    'today.steps.followup.todo': 'Draft the follow-up while the interview context is still fresh.',
    'today.steps.followup.draft': 'Draft Follow-up',
    'today.cards.interview.title': 'Interview Prep',
    'today.cards.interview.desc': 'Practice interviews, predict likely questions, shape STAR stories, polish your tone, draft follow-ups, and prepare your elevator pitch.',
    'today.cards.interview.cta': 'Open Interview Prep',
    'today.cards.interview.badge': 'Prepare',
    'today.cards.tools.title': 'Prep Tools',
    'today.cards.tools.desc': 'Run gap analysis, check your resume, improve cover letters, audit LinkedIn, review visual design, and reframe transferable skills.',
    'today.cards.tools.cta': 'Open Prep Tools',
    'today.cards.tools.badge': 'Documents',
    'today.cards.reviews.title': 'Reviews Due',
    'today.cards.reviews.desc': '{count} learning reviews are due today. Keep your prep sharp while applications are moving.',
    'today.cards.reviews.cta': 'Open Learning',
    'today.cards.reviews.badge': 'Learning',
    'today.cards.pipeline.title': 'Review Your Pipeline',
    'today.cards.pipeline.desc': '{count} applications are in play. Use Applications to switch focus, update stages, or catch stalled roles.',
    'today.cards.pipeline.cta': 'Open Applications',
    'today.cards.pipeline.badge': 'Pipeline',
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage plan, AI access, resume, language, voice, and local data.',
    'settings.languageTitle': 'Language & Voice',
    'settings.languageCopy': 'Choose the interface language and the browser voice JobSensei uses for spoken answers.',
    'settings.interfaceLanguage': 'Interface language',
    'settings.voice': 'AI voice',
    'settings.voiceAuto': 'Auto voice for selected language',
    'settings.voicePreview': 'Preview voice',
    'settings.voiceExact': 'Voice match found.',
    'settings.voiceRelated': 'Using a related voice for this language.',
    'settings.voiceFallback': 'No matching voice found. JobSensei will use a fallback voice, so speech may sound weird.',
    'settings.voiceNone': 'No browser voices are available yet.',
    'settings.voiceNote': 'Voice note',
    'settings.planAccess': 'Plan And AI Access',
    'settings.resumeTitle': 'Resume / CV',
    'settings.projectData': 'Project Data',
    'settings.profile': 'Your Profile',
    'voice.placeholder': 'Type your message...',
    'voice.listening': 'Listening...',
    'voice.paused': 'Paused - tap mic to continue',
    'voice.discard': 'Discard',
    'voice.doneSend': 'Done - Send',
    'voice.speakNow': 'Speak now - words appear when recognised...',
    'voice.submitHelp': 'Done - Send to submit · Discard to cancel',
    'voice.muted': 'AI voice is muted - tap the speaker in the top bar to unmute',
    'voice.speaking': 'Speaking - tap speaker to stop',
  },
  ru: {
    'nav.today': 'Сегодня',
    'nav.applications': 'Заявки',
    'nav.learning': 'Обучение',
    'nav.settings': 'Настройки',
    'nav.projects': 'Проекты',
    'nav.apps': 'Заявки',
    'topbar.guide': 'Гид',
    'topbar.start': 'Старт',
    'topbar.aiConnected': 'AI подключен',
    'topbar.locked': 'Закрыто',
    'topbar.thinking': 'Думаю...',
    'topbar.sensei': 'Сенсей',
    'topbar.drill': 'Дрилл',
    'gate.title': 'Сначала добавьте заявку',
    'gate.copy': '{section} работает лучше, когда JobSensei знает компанию, роль и описание вакансии. Сначала создайте или захватите одну реальную заявку, затем инструменты откроются с правильным контекстом.',
    'gate.add': 'Добавить заявку',
    'gate.back': 'Назад к Сегодня',
    'today.hello': 'Привет, {name}',
    'today.subtitle': 'Одно место для следующего реального шага в поиске работы.',
    'today.activeFocus': 'Активный фокус',
    'today.startFirst': 'Начните первую заявку',
    'today.startCopy': 'Сначала добавьте компанию и роль. JobSensei превратит это в одно рабочее пространство с исследованием, подготовкой, практикой и follow-up.',
    'today.openApplications': 'Открыть заявки',
    'today.applications': 'Заявки',
    'today.workspaceProgress': 'Прогресс workspace',
    'today.pickApplication': 'Выберите заявку для начала',
    'today.rolesInPlay': 'Роли в работе',
    'today.mockInterviews': 'Мок-интервью',
    'today.savedProject': 'Сохранено в проекте',
    'today.reviewsDue': 'Повторы сегодня',
    'today.noReviews': 'Сегодня повторов нет',
    'today.firstStep': 'Первый шаг',
    'today.firstStepTitle': 'Добавьте одну реальную заявку, чтобы открыть workspace',
    'today.firstStepCopy': 'Начните с компании, роли и описания вакансии. После этого Interview Prep, Prep Tools, research, follow-up и offer comparison будут связаны с этой заявкой.',
    'today.prepHubs': 'Центры подготовки',
    'today.prepHubsCopy': 'Два пути: практика интервью или подготовка документов/профиля.',
    'settings.title': 'Настройки',
    'settings.subtitle': 'План, AI-доступ, резюме, язык, голос и локальные данные.',
    'projects.exportCurrentProject': 'Экспорт проекта',
    'settings.languageTitle': 'Язык и голос',
    'settings.languageCopy': 'Выберите язык интерфейса и голос браузера для озвучки ответов.',
    'settings.interfaceLanguage': 'Язык интерфейса',
    'settings.voice': 'Голос AI',
    'settings.voiceAuto': 'Авто-голос для выбранного языка',
    'settings.voicePreview': 'Проверить голос',
    'settings.voiceExact': 'Голос найден.',
    'settings.voiceRelated': 'Используется похожий голос.',
    'settings.voiceFallback': 'Подходящий голос не найден. Будет fallback, речь может звучать странно.',
    'settings.voiceNone': 'Голоса браузера пока недоступны.',
    'settings.voiceNote': 'Заметка о голосе',
    'settings.planAccess': 'План и AI-доступ',
    'settings.resumeTitle': 'Резюме / CV',
    'settings.projectData': 'Данные проекта',
    'settings.profile': 'Профиль',
    'voice.placeholder': 'Введите сообщение...',
  },
  bg: {
    'nav.today': 'Днес',
    'nav.applications': 'Кандидатури',
    'nav.learning': 'Учене',
    'nav.settings': 'Настройки',
    'nav.projects': 'Проекти',
    'nav.apps': 'Кандидатури',
    'topbar.guide': 'Гид',
    'topbar.start': 'Старт',
    'topbar.aiConnected': 'AI свързан',
    'topbar.locked': 'Заключено',
    'topbar.thinking': 'Мисля...',
    'topbar.sensei': 'Сенсей',
    'topbar.drill': 'Drill',
    'gate.title': 'Първо добави кандидатура',
    'gate.copy': '{section} работи най-добре, когато JobSensei знае компанията, ролята и описанието на позицията. Първо създай или capture-ни една реална кандидатура, после инструментите ще се отключат с правилния контекст.',
    'gate.add': 'Добави кандидатура',
    'gate.back': 'Назад към Днес',
    'today.hello': 'Здравей, {name}',
    'today.subtitle': 'Едно място за следващия реален ход в търсенето на работа.',
    'today.activeFocus': 'Активен фокус',
    'today.startFirst': 'Започни първата кандидатура',
    'today.startCopy': 'Първо добави компания и роля. JobSensei ще ги превърне в workspace с research, подготовка, практика и follow-up.',
    'today.openApplications': 'Отвори кандидатури',
    'today.applications': 'Кандидатури',
    'today.workspaceProgress': 'Прогрес в workspace',
    'today.pickApplication': 'Избери кандидатура, за да започнеш',
    'today.rolesInPlay': 'Активни роли',
    'today.mockInterviews': 'Mock интервюта',
    'today.savedProject': 'Запазено в проекта',
    'today.reviewsDue': 'Повторения днес',
    'today.noReviews': 'Няма повторения за днес',
    'today.firstStep': 'Първа стъпка',
    'today.firstStepTitle': 'Добави една реална кандидатура, за да отключиш workspace-а',
    'today.firstStepCopy': 'Започни с компания, роля и job description. После Interview Prep, Prep Tools, research, follow-up и offer comparison ще се вържат към тази кандидатура.',
    'today.prepHubs': 'Подготовка',
    'today.prepHubsCopy': 'Две ясни посоки: интервю практика или документи/профил.',
    'settings.title': 'Настройки',
    'settings.subtitle': 'Управлявай план, AI достъп, CV, език, глас и локални данни.',
    'projects.exportCurrentProject': 'Експорт на проекта',
    'settings.languageTitle': 'Език и глас',
    'settings.languageCopy': 'Избери език на интерфейса и browser voice за AI отговорите.',
    'settings.interfaceLanguage': 'Език на интерфейса',
    'settings.voice': 'AI глас',
    'settings.voiceAuto': 'Автоматичен глас за езика',
    'settings.voicePreview': 'Пробвай гласа',
    'settings.voiceExact': 'Намерен е глас за езика.',
    'settings.voiceRelated': 'Използва се близък глас.',
    'settings.voiceFallback': 'Няма български voice в браузъра. JobSensei ще използва fallback и може да звучи странно.',
    'settings.voiceNone': 'Няма налични browser voices.',
    'settings.voiceNote': 'Бележка за гласа',
    'settings.planAccess': 'План и AI достъп',
    'settings.resumeTitle': 'Резюме / CV',
    'settings.projectData': 'Проектни данни',
    'settings.profile': 'Твоят профил',
    'voice.placeholder': 'Напиши съобщение...',
  },
  es: {
    'nav.today': 'Hoy',
    'nav.applications': 'Aplicaciones',
    'nav.learning': 'Aprendizaje',
    'nav.settings': 'Ajustes',
    'nav.projects': 'Proyectos',
    'nav.apps': 'Apps',
    'topbar.guide': 'Guía',
    'topbar.start': 'Inicio',
    'topbar.aiConnected': 'AI conectado',
    'topbar.locked': 'Bloqueado',
    'topbar.thinking': 'Pensando...',
    'gate.title': 'Añade una aplicación primero',
    'gate.copy': '{section} funciona mejor cuando JobSensei conoce la empresa, el rol y la descripción del puesto. Crea o captura una aplicación real primero; luego las herramientas se desbloquean con el contexto correcto.',
    'gate.add': 'Añadir aplicación',
    'gate.back': 'Volver a Hoy',
    'today.hello': 'Hola, {name}',
    'today.subtitle': 'Un lugar para ver el siguiente paso real en tu búsqueda.',
    'today.activeFocus': 'Foco activo',
    'today.startFirst': 'Empieza tu primera aplicación',
    'today.openApplications': 'Abrir aplicaciones',
    'today.applications': 'Aplicaciones',
    'today.firstStep': 'Primer paso',
    'today.firstStepTitle': 'Añade una aplicación real para desbloquear el workspace',
    'settings.title': 'Ajustes',
    'settings.subtitle': 'Gestiona plan, acceso AI, CV, idioma, voz y datos locales.',
    'projects.exportCurrentProject': 'Exportar proyecto',
    'settings.languageTitle': 'Idioma y voz',
    'settings.languageCopy': 'Elige el idioma de la interfaz y la voz del navegador para respuestas habladas.',
    'settings.interfaceLanguage': 'Idioma de interfaz',
    'settings.voice': 'Voz AI',
    'settings.voiceAuto': 'Voz automática para el idioma',
    'settings.voicePreview': 'Probar voz',
    'settings.voiceExact': 'Voz compatible encontrada.',
    'settings.voiceRelated': 'Se está usando una voz relacionada para este idioma.',
    'settings.voiceFallback': 'No se encontró una voz compatible. JobSensei usará una voz alternativa.',
    'settings.voiceNone': 'Aún no hay voces del navegador disponibles.',
    'settings.voiceNote': 'Nota sobre la voz',
    'voice.placeholder': 'Escribe tu mensaje...',
  },
  fr: {
    'nav.today': 'Aujourd’hui',
    'nav.applications': 'Candidatures',
    'nav.learning': 'Apprentissage',
    'nav.settings': 'Paramètres',
    'nav.projects': 'Projets',
    'nav.apps': 'Apps',
    'topbar.guide': 'Guide',
    'topbar.start': 'Démarrer',
    'topbar.aiConnected': 'AI connectée',
    'topbar.locked': 'Verrouillé',
    'topbar.thinking': 'Réflexion...',
    'gate.title': 'Ajoutez d’abord une candidature',
    'gate.copy': '{section} fonctionne mieux lorsque JobSensei connaît l’entreprise, le poste et la JD. Créez ou capturez d’abord une vraie candidature, puis les outils se déverrouilleront avec le bon contexte.',
    'gate.add': 'Ajouter une candidature',
    'gate.back': 'Retour à Aujourd’hui',
    'today.hello': 'Bonjour, {name}',
    'today.subtitle': 'Un seul endroit pour voir la prochaine vraie action dans votre recherche d’emploi.',
    'today.activeFocus': 'Focus actif',
    'today.startFirst': 'Commencez votre première candidature',
    'today.openApplications': 'Ouvrir les candidatures',
    'today.applications': 'Candidatures',
    'today.firstStep': 'Première étape',
    'today.firstStepTitle': 'Ajoutez une vraie candidature pour déverrouiller le workspace',
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Gérez le plan, l’accès AI, le CV, la langue, la voix et les données locales.',
    'projects.exportCurrentProject': 'Exporter le projet',
    'settings.languageTitle': 'Langue et voix',
    'settings.languageCopy': 'Choisissez la langue de l’interface et la voix du navigateur pour les réponses parlées.',
    'settings.interfaceLanguage': 'Langue de l’interface',
    'settings.voice': 'Voix AI',
    'settings.voiceAuto': 'Voix automatique pour la langue sélectionnée',
    'settings.voicePreview': 'Tester la voix',
    'settings.voiceExact': 'Voix correspondante trouvée.',
    'settings.voiceRelated': 'Une voix proche est utilisée pour cette langue.',
    'settings.voiceFallback': 'Aucune voix compatible trouvée. JobSensei utilisera une voix de secours.',
    'settings.voiceNone': 'Aucune voix de navigateur n’est encore disponible.',
    'settings.voiceNote': 'Note sur la voix',
    'voice.placeholder': 'Écrivez votre message...',
  },
  it: {
    'nav.today': 'Oggi',
    'nav.applications': 'Candidature',
    'nav.learning': 'Studio',
    'nav.settings': 'Impostazioni',
    'nav.projects': 'Progetti',
    'nav.apps': 'App',
    'topbar.guide': 'Guida',
    'topbar.aiConnected': 'AI connessa',
    'topbar.locked': 'Bloccato',
    'gate.title': 'Aggiungi prima una candidatura',
    'gate.add': 'Aggiungi candidatura',
    'today.hello': 'Ciao, {name}',
    'settings.title': 'Impostazioni',
    'settings.subtitle': 'Gestisci piano, accesso AI, CV, lingua, voce e dati locali.',
    'projects.exportCurrentProject': 'Esporta progetto',
    'settings.languageTitle': 'Lingua e voce',
    'settings.interfaceLanguage': 'Lingua interfaccia',
    'settings.voice': 'Voce AI',
    'settings.voiceAuto': 'Voce automatica per la lingua',
    'settings.voicePreview': 'Prova voce',
    'settings.voiceExact': 'Voce corrispondente trovata.',
    'settings.voiceRelated': 'Viene usata una voce correlata per questa lingua.',
    'settings.voiceFallback': 'Nessuna voce compatibile trovata. JobSensei userà una voce di fallback.',
    'settings.voiceNone': 'Nessuna voce del browser è ancora disponibile.',
    'settings.voiceNote': 'Nota sulla voce',
    'voice.placeholder': 'Scrivi il tuo messaggio...',
  },
  pt: {
    'nav.today': 'Hoje',
    'nav.applications': 'Candidaturas',
    'nav.learning': 'Aprendizagem',
    'nav.settings': 'Configurações',
    'nav.projects': 'Projetos',
    'nav.apps': 'Apps',
    'topbar.guide': 'Guia',
    'topbar.start': 'Iniciar',
    'topbar.aiConnected': 'AI conectada',
    'topbar.locked': 'Bloqueado',
    'topbar.thinking': 'Pensando...',
    'gate.title': 'Adicione uma candidatura primeiro',
    'gate.copy': '{section} funciona melhor quando o JobSensei conhece a empresa, o cargo e a JD. Crie ou capture uma candidatura real primeiro; depois, as ferramentas serão desbloqueadas com o contexto correto.',
    'gate.add': 'Adicionar candidatura',
    'gate.back': 'Voltar para Hoje',
    'today.hello': 'Olá, {name}',
    'today.subtitle': 'Um só lugar para ver o próximo passo real na sua busca por emprego.',
    'today.activeFocus': 'Foco ativo',
    'today.startFirst': 'Comece sua primeira candidatura',
    'today.openApplications': 'Abrir candidaturas',
    'today.applications': 'Candidaturas',
    'today.firstStep': 'Primeiro passo',
    'today.firstStepTitle': 'Adicione uma candidatura real para desbloquear o workspace',
    'settings.title': 'Configurações',
    'settings.subtitle': 'Gerencie plano, acesso AI, CV, idioma, voz e dados locais.',
    'projects.exportCurrentProject': 'Exportar projeto',
    'settings.languageTitle': 'Idioma e voz',
    'settings.languageCopy': 'Escolha o idioma da interface e a voz do navegador para respostas faladas.',
    'settings.interfaceLanguage': 'Idioma da interface',
    'settings.voice': 'Voz AI',
    'settings.voiceAuto': 'Voz automática para o idioma selecionado',
    'settings.voicePreview': 'Testar voz',
    'settings.voiceExact': 'Voz correspondente encontrada.',
    'settings.voiceRelated': 'Usando uma voz relacionada para este idioma.',
    'settings.voiceFallback': 'Nenhuma voz compatível encontrada. O JobSensei usará uma voz alternativa.',
    'settings.voiceNone': 'Nenhuma voz do navegador está disponível ainda.',
    'settings.voiceNote': 'Nota sobre a voz',
    'voice.placeholder': 'Digite sua mensagem...',
  },
  pl: {
    'nav.today': 'Dzisiaj',
    'nav.applications': 'Aplikacje',
    'nav.learning': 'Nauka',
    'nav.settings': 'Ustawienia',
    'nav.projects': 'Projekty',
    'nav.apps': 'Aplikacje',
    'topbar.guide': 'Przewodnik',
    'topbar.aiConnected': 'AI połączone',
    'topbar.locked': 'Zablokowane',
    'gate.title': 'Najpierw dodaj aplikację',
    'gate.add': 'Dodaj aplikację',
    'today.hello': 'Cześć, {name}',
    'settings.title': 'Ustawienia',
    'settings.subtitle': 'Zarządzaj planem, dostępem AI, CV, językiem, głosem i danymi lokalnymi.',
    'projects.exportCurrentProject': 'Eksport projektu',
    'settings.languageTitle': 'Język i głos',
    'settings.interfaceLanguage': 'Język interfejsu',
    'settings.voice': 'Głos AI',
    'settings.voiceAuto': 'Automatyczny głos dla języka',
    'settings.voicePreview': 'Test głosu',
    'settings.voiceExact': 'Znaleziono pasujący głos.',
    'settings.voiceRelated': 'Używany jest pokrewny głos dla tego języka.',
    'settings.voiceFallback': 'Nie znaleziono pasującego głosu. JobSensei użyje głosu zastępczego.',
    'settings.voiceNone': 'Głosy przeglądarki nie są jeszcze dostępne.',
    'settings.voiceNote': 'Uwaga dotycząca głosu',
    'voice.placeholder': 'Wpisz wiadomość...',
  },
  de: {
    'nav.today': 'Heute',
    'nav.applications': 'Bewerbungen',
    'nav.learning': 'Lernen',
    'nav.settings': 'Einstellungen',
    'nav.projects': 'Projekte',
    'nav.apps': 'Apps',
    'topbar.guide': 'Guide',
    'topbar.aiConnected': 'AI verbunden',
    'topbar.locked': 'Gesperrt',
    'gate.title': 'Zuerst eine Bewerbung hinzufügen',
    'gate.add': 'Bewerbung hinzufügen',
    'today.hello': 'Hallo, {name}',
    'settings.title': 'Einstellungen',
    'settings.subtitle': 'Plan, AI-Zugang, Lebenslauf, Sprache, Stimme und lokale Daten verwalten.',
    'projects.exportCurrentProject': 'Projekt exportieren',
    'settings.languageTitle': 'Sprache und Stimme',
    'settings.languageCopy': 'Wählen Sie die Oberflächensprache und die Browser-Stimme für gesprochene Antworten.',
    'settings.interfaceLanguage': 'Oberflächensprache',
    'settings.voice': 'AI-Stimme',
    'settings.voiceAuto': 'Automatische Stimme für diese Sprache',
    'settings.voicePreview': 'Stimme testen',
    'settings.voiceExact': 'Passende Stimme gefunden.',
    'settings.voiceRelated': 'Es wird eine verwandte Stimme für diese Sprache verwendet.',
    'settings.voiceFallback': 'Keine passende Stimme gefunden. JobSensei nutzt eine Ersatzstimme.',
    'settings.voiceNone': 'Noch keine Browser-Stimmen verfügbar.',
    'settings.voiceNote': 'Hinweis zur Stimme',
    'voice.placeholder': 'Nachricht eingeben...',
  },
}

const LanguageContext = createContext(null)
const SUPPORTED_LANGUAGE_CODES = new Set(LANGUAGE_OPTIONS.map(option => option.code))
const LEGACY_LANGUAGE_MAP = {
  'es-US': 'es-ES',
  'pt-PT': 'pt-BR',
}
const FEMALE_VOICE_HINTS = [
  'female', 'woman', 'zira', 'samantha', 'karen', 'moira', 'tessa', 'victoria', 'fiona',
  'serena', 'susan', 'joanna', 'jenny', 'aria', 'ana', 'maria', 'monica', 'elvira',
  'hortense', 'amelie', 'aurelie', 'audrey', 'elsa', 'alice', 'paulina', 'zosia',
  'helia', 'joana', 'ines', 'irina', 'milena', 'katja', 'anna', 'daria',
]
const MALE_VOICE_HINTS = [
  'male', 'man', 'david', 'daniel', 'mark', 'george', 'jorge', 'diego', 'thomas',
  'paul', 'yuri', 'fred', 'joris', 'stefan', 'pavel',
]

function dictionaryKey(option) {
  return option?.dictionary || option?.code || 'en'
}

function interpolate(template, vars = {}) {
  return String(template).replace(/\{(\w+)\}/g, (_, key) => vars[key] ?? '')
}

function normalizeVoiceLang(lang = '') {
  return String(lang || '').replace(/_/g, '-').toLowerCase()
}

export function findVoiceForLanguage(option, voices, preferredVoiceName = '') {
  if (!Array.isArray(voices) || voices.length === 0) return null
  if (preferredVoiceName) {
    const selected = voices.find(voice => voice.name === preferredVoiceName)
    if (selected) return selected
  }

  const lang = option?.speechLang || 'en-US'
  const normalizedLang = normalizeVoiceLang(lang)
  const baseLang = normalizedLang.split('-')[0]
  const searchNames = option?.voiceSearch || []
  const excludedVoiceLangs = option?.excludedVoiceLangs || []
  const excludedVoiceNames = option?.excludedVoiceNames || []

  const nameIncludes = (voice, hint) => voice.name?.toLowerCase().includes(hint.toLowerCase())
  const isAllowedVoice = voice => (
    !excludedVoiceLangs.some(lang => normalizeVoiceLang(voice.lang) === normalizeVoiceLang(lang))
    && !excludedVoiceNames.some(name => nameIncludes(voice, name))
  )
  const hasFemaleHint = voice => FEMALE_VOICE_HINTS.some(hint => nameIncludes(voice, hint))
  const hasMaleHint = voice => MALE_VOICE_HINTS.some(hint => nameIncludes(voice, hint))
  const pickBest = (pool, useSearchNames = true) => {
    const allowedPool = pool.filter(isAllowedVoice)
    if (!allowedPool.length) return null
    if (useSearchNames) {
      for (const name of searchNames) {
        const match = allowedPool.find(voice => voice.name === name || nameIncludes(voice, name))
        if (match) return match
      }
    }
    return allowedPool.find(hasFemaleHint)
      || allowedPool.find(voice => !hasMaleHint(voice))
      || allowedPool[0]
  }

  const exactLang = voices.filter(voice => normalizeVoiceLang(voice.lang) === normalizedLang)
  const relatedLang = voices.filter((voice) => {
    const voiceLang = normalizeVoiceLang(voice.lang)
    return voiceLang === baseLang || voiceLang.startsWith(`${baseLang}-`)
  })
  const englishFallback = voices.filter(voice => normalizeVoiceLang(voice.lang).startsWith('en'))

  return pickBest(exactLang)
    || pickBest(relatedLang)
    || pickBest(englishFallback, false)
    || pickBest(voices, false)
}

function getVoiceSupport(option, voice, voices) {
  if (!voices.length) return 'none'
  if (!voice) return 'none'
  const voiceLang = normalizeVoiceLang(voice.lang)
  const optionLang = normalizeVoiceLang(option.speechLang)
  if (voiceLang === optionLang) return 'exact'
  if (voiceLang.split('-')[0] === optionLang.split('-')[0]) return 'related'
  return 'fallback'
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem('js_language')
    if (LEGACY_LANGUAGE_MAP[saved]) return LEGACY_LANGUAGE_MAP[saved]
    return SUPPORTED_LANGUAGE_CODES.has(saved) ? saved : 'en'
  })
  const [voiceName, setVoiceNameState] = useState('')
  const [voices, setVoices] = useState([])

  useEffect(() => {
    if (!window.speechSynthesis) return
    const loadVoices = () => setVoices(window.speechSynthesis.getVoices() || [])
    loadVoices()
    window.speechSynthesis.addEventListener?.('voiceschanged', loadVoices)
    window.speechSynthesis.onvoiceschanged = loadVoices
    return () => window.speechSynthesis.removeEventListener?.('voiceschanged', loadVoices)
  }, [])

  const languageOption = LANGUAGE_OPTIONS.find(option => option.code === language) || LANGUAGE_OPTIONS[0]
  const dictKey = dictionaryKey(languageOption)
  const activeVoice = useMemo(
    () => findVoiceForLanguage(languageOption, voices, voiceName),
    [languageOption, voiceName, voices],
  )
  const voiceSupport = getVoiceSupport(languageOption, activeVoice, voices)

  useEffect(() => {
    document.documentElement.lang = languageOption.speechLang || languageOption.code || 'en'
    localStorage.setItem('js_language', languageOption.code)
    localStorage.removeItem('js_voice_name')
  }, [languageOption])

  const t = (key, vars) => {
    const value = localizationPatches[dictKey]?.[key]
      || TRANSLATIONS[dictKey]?.[key]
      || localizationPatches.en[key]
      || TRANSLATIONS.en[key]
      || key
    return interpolate(value, vars)
  }

  function setLanguage(nextLanguage) {
    const safeLanguage = SUPPORTED_LANGUAGE_CODES.has(nextLanguage) ? nextLanguage : 'en'
    setLanguageState(safeLanguage)
    setVoiceNameState('')
    localStorage.setItem('js_language', safeLanguage)
    localStorage.removeItem('js_voice_name')
  }

  function setVoiceName(nextVoiceName) {
    setVoiceNameState(nextVoiceName)
    if (nextVoiceName) localStorage.setItem('js_voice_name', nextVoiceName)
    else localStorage.removeItem('js_voice_name')
  }

  const value = {
    language,
    setLanguage,
    languageOption,
    languages: LANGUAGE_OPTIONS,
    t,
    voices,
    voiceName,
    setVoiceName,
    activeVoice,
    voiceSupport,
    speechLang: languageOption.speechLang,
    recognitionLang: languageOption.recognitionLang,
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  return useContext(LanguageContext)
}
